Controllers/HelpSupportController.cs
using Bina.Data;
using Bina.Models;
using Microsoft.AspNetCore.Mvc;

namespace Bina.Controllers
{
    /*   public class HelpSupportController : Controller
       {
           public IActionResult HelpSupport()
           {
               return View(new HelpSupport());
           }

           [HttpPost]
           public IActionResult HelpSupport(HelpSupport model)
           {
               if (ModelState.IsValid)
               {
                   return RedirectToAction("ConfirmationPage");
               }
               else
               {
                   return View(model);
               }

           }

           public IActionResult ConfirmationPage()
           {
               return View();
           }
       }*/

    /*
    public class HelpSupportController : Controller
    {
        private readonly ILogger<HelpSupportController> _logger;

        public HelpSupportController(ILogger<HelpSupportController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();

        }
    }
    */
    public class HelpSupportController : Controller
    {
        private readonly ILogger<HelpSupportController> _logger; //ILogger ghi log cho HelpSupportController
        private readonly Ft1Context _ft1;

        public HelpSupportController(ILogger<HelpSupportController> logger, Ft1Context ft1)
        {
            _logger = logger; // gán giá trị _logger cho Ilogger
            _ft1 = ft1;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View(); //hiển thị form gửi support
        }

        [HttpPost]
        public IActionResult HelpSupport(HelpAndSupport model)
        {
            if (ModelState.IsValid)
            {
                model.CreatedAt = DateTime.Now;
                _ft1.HelpAndSupports.Add(model);
                _ft1.SaveChanges();
                return RedirectToAction(nameof(ConfirmationPage));
            }
            return View(model);
        }


        public IActionResult ConfirmationPage()
        {
            return View();
        }
    }
}

Areas/Coordinator/Views/Shared/_FooterPartial.cshtml
    <!-- Footer Start -->
    <nav class="navbar navbar-light bg-light">
        <div class="container">
           <div>
               <h2>
                    <a class="navbar-brand" style="color:#ffff">Follow Contoso 👌👌</a>
               </h2>
           </div>
           
            @* <form class="d-flex">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form> *@
        </div>
    </nav>
    <footer class="page-footer">
        <div class="container">
            <div class="row justify-content-center mb-5">
                <div class="col-lg-3 py-3">
                    <h3>Uni<span class="text-primary">Learn</span></h3>
                    <p><a href="#">All retail products</a></p>

                    <p><a href="#">Home</a></p>
                    <p><a href="#">Commercial</a></p>
                </div>
                <div class="col-lg-3 py-3">
                    <h5>Contoso Store</h5>
                    <ul class="footer-menu">
                        <li><a href="#">View account</a></li>
                        <li><a href="#">Order tracking</a></li>
                        <li><a href="#">Returns</a></li>
                        <li><a href="#">Sales & Support</a></li>
                       
                    </ul>
                </div>
                <div class="col-lg-3 py-3">
                    <h5>Download</h5>
                    <ul class="footer-menu">
                        <li><a href="#">Product manuals</a></li>
                        <li><a href="#">White papers</a></li>
                        <li><a href="#">Contoso Apps</a></li
                    </ul>
                </div>
                <div class="col-lg-3 py-3">
                    <h5>Company</h5>
                    <ul class="footer-menu">
                        <li><a href="#">Careers at Contoso</a></li>
                        <li><a href="#">About Contoso</a></li>
                        <li><a href="#">Site map</a></li
                    </ul>
                </div>

               @*  <div class="col-lg-3 py-3">
                    <h5>Subscribe</h5>
                    <form action="#">
                        <input type="text" class="form-control" placeholder="Enter your mail..">
                    </form>

                    <div class="sosmed-button mt-4">
                        <a href="#"><span class="mai-logo-facebook-f"></span></a>
                        <a href="#"><span class="mai-logo-twitter"></span></a>
                        <a href="#"><span class="mai-logo-google"></span></a>
                        <a href="#"><span class="mai-logo-linkedin"></span></a>
                    </div>
                </div> *@
            </div>

            <div class="row minh_rowFooter">
                <div class="col-sm-6 py-2">
                    <p id="copyright">&copy; 2024 <a href="https://macodeid.com/">FlashTeam</a>. All rights reserved</p>
                </div>
                <div class="col-sm-6 py-2 text-right minh_rowFooterEnd">
                    
                    <div class="d-inline-block px-3">
                        <a href="#">Contact Us</a>
                    </div>
                    <div class="d-inline-block px-3">
                        <a href="#">Privacy & cookies</a>
                    </div>
                    <div class="d-inline-block px-3">
                        <a href="#">Terms of use</a>
                    </div>
                    <div class="d-inline-block px-3">
                        <a href="#">2016 Contoso</a>
                    </div>
                </div>
            </div>
        </div> 
    </footer> 
    <!-- Footer End -->

Areas/Coordinator/Views/Shared/_HeaderPartial.cshtml
<!-- App header starts -->
<div class="app-header d-flex align-items-center">

    <!-- Container starts -->
    <div class="container">

        <!-- Row starts -->
        <div class="row">
            <div class="col-md-3 col-2">

                <!-- App brand starts -->
                <div class="app-brand">
                    <a class="d-lg-block d-none" asp-area="Coordinator" asp-controller="Home" asp-action="Index">
                        <img src="~/img/logo.svg" class="logo" alt="Bootstrap Gallery" />
                    </a>
                    <a class="d-lg-none d-md-block" asp-area="Coordinator" asp-controller="Home" asp-action="Index">
                        <img src="~/img/logo-sm.svg" class="logo" alt="Bootstrap Gallery" />
                    </a>
                </div>
                <!-- App brand ends -->

            </div>

            <div class="col-md-9 col-10">
                <!-- App header actions start -->
                <div class="header-actions d-flex align-items-center justify-content-end">
                    <div class="dropdown ms-2">

                        <a class="dropdown-toggle d-flex align-items-center user-settings" href="#!" role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            @if (!string.IsNullOrEmpty(Context.Session.GetString("UserName")))
                            {
                                <span class="d-none d-md-block">Hello, @Context.Session.GetString("UserName")</span>
                            }
                            else if (!User.Identity.IsAuthenticated)
                            {
                                <span class="d-none d-md-block">Hello, @User.Identity.Name</span>
                            }
                            <img src="~/img/user3.png" class="img-3x m-2 me-0 rounded-5" alt="Bootstrap Gallery" />
                        </a>

                        <div class="dropdown-menu dropdown-menu-end dropdown-menu-sm shadow-sm gap-3" style="">
                            <a class="dropdown-item d-flex align-items-center py-2" href="agent-profile.html">
                                <i class="bi bi-person-vcard" style="margin-right: 10px"></i>User Profile
                            </a>
                            <a class="dropdown-item d-flex align-items-center py-2" href="account-settings.html">
                                <i class="bi bi-gear" style="margin-right: 10px"></i>Account
                                Settings
                            </a>
                            <a class="dropdown-item d-flex align-items-center py-2" asp-area="" asp-controller="Logins" asp-action="Logout">
                                <i class="bi bi-box-arrow-right" style="margin-right: 10px"></i>Logout
                            </a>
                        </div>
                    </div>

                    <!-- Toggle Menu starts -->
                    <button class="btn btn-success btn-sm ms-3 d-lg-none d-md-block" type="button"
                            data-bs-toggle="offcanvas" data-bs-target="#MobileMenu">
                        <i class="bi bi-list"></i>
                    </button>
                    <!-- Toggle Menu ends -->

                </div>
                <!-- App header actions end -->

            </div>
        </div>
        <!-- Row ends -->

    </div>
    <!-- Container ends -->

</div>
<!-- App header ends -->
<!-- App navbar starts -->
<nav class="navbar navbar-expand-lg p-0">
    <div class="container">
        <div class="offcanvas offcanvas-end" id="MobileMenu">
            <div class="offcanvas-header">
                <h5 class="offcanvas-title semibold">Navigation</h5>
                <button type="button" class="btn btn-danger btn-sm" data-bs-dismiss="offcanvas">
                    <i class="icon-clear"></i>
                </button>
            </div>
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item  active-link">
                    <a class="nav-link" role="button" asp-area="Coordinator" asp-controller="Home" asp-action="Index"
                       aria-expanded="false">
                        <i class="bi bi-house-door" style="margin-right: 10px"></i>
                        Dashboards
                    </a>
                    @*   <ul class="dropdown-menu">
                    <li>
                    <a class="dropdown-item current-page" asp-area="" asp-controller="Home" asp-action="Index">Analytics</a>
                    </li>
                    <li>
                    <a class="dropdown-item" href="#">
                    <span>Reports</span>
                    </a>
                    </li>
                    </ul> *@
                </li>

                <li class="nav-item">
                    @* <a class="nav-link" href="#"><i class="bi bi-book" style="margin-right: 10px"></i> Article Management </a> *@
                </li>

                <li class="nav-item">
                    <a class="nav-link" asp-area="Coordinator" asp-controller="Faculty" asp-action="Index">
                        <i class="bi bi-people-fill" style="margin-right: 10px"></i>Faculty Management
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" asp-area="Coordinator" asp-controller="Users" asp-action="Index">
                        <i class="bi bi-people-fill" style="margin-right: 10px"></i>User Management
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="#"><i class="bi bi-sliders" style="margin-right: 10px"></i> System configuration </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="#"><i class="bi bi-journal-bookmark" style="margin-right: 10px"></i> System log </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" asp-area="Coordinator" asp-controller="HelpSupport" asp-action="Index"> Help and Support </a>
                </li>

                @* <partial name="_LoginPartial" /> *@

            </ul>
        </div>
    </div>
</nav>
<!-- App Navbar ends -->

Areas/Coordinator/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bina</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/icomoon.css" />
    <link rel="stylesheet" href="~/css/main.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Bina.styles.css" asp-append-version="true" />

    <!--Font-awesome-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css" integrity="sha384-4LISF5TTJX/fLmGSxO53rV4miRxdg84mZsxmO8Rx5jGtp/LbrixFETvWa5a6sESd" crossorigin="anonymous">

    <!-- Chart.js -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

    <style>
        #MinhHomePage th, #MinhHomePage td {
            text-align: center;
            vertical-align: middle;
            height: 80px; /* Thiết lập chiều cao cho mỗi ô để đủ không gian căn giữa */
        }

        #Quynh .confirmation-message {
            background-color: #fff;
            padding: 20px;
            border-radius: 5px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }
    </style>

</head>
<body>
   
    <!-- Import Header -->
    @Html.Partial("_HeaderPartial")

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

     <!-- JQuery AJAX -->
    <script src="~/lib/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.js"></script>


    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

    <!-- Body Page -->  
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <!-- Import Footer -->
    @Html.Partial("_FooterPartial")


    </footer>

    <!-- Import Data Analysis Chart -->
    <script>
        // Dữ liệu cho biểu đồ
        const data = {
            labels: ['Unpublished submissions', 'The submissions are published', 'Total number of papers submitted'],
            datasets: [{
                label: 'Number of Articles',
                data: [14, 19, 19], // Tổng số lượng từ Người A, B, C
                backgroundColor: [
                    'rgba(255, 99, 132, 0.2)',
                    'rgba(54, 162, 235, 0.2)',
                    'rgba(255, 206, 86, 0.2)'
                ],
                borderColor: [
                    'rgba(255, 99, 132, 1)',
                    'rgba(54, 162, 235, 1)',
                    'rgba(255, 206, 86, 1)'
                ],
                borderWidth: 1
            }]
        };

        // Cấu hình biểu đồ
        const config = {
            type: 'pie',
            data: data,
            options: {
                responsive: true,
                maintainAspectRatio: false,
            }
        };

        // Tạo biểu đồ
        const myPieChart = new Chart(
            document.getElementById('myPieChart'),
            config
        );
    </script>
    

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>